import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import Header from "./components/sidenav/Header";
import HeaderMobile from "./components/sidenav/Header-Mobile";
import SideNav from "./components/sidenav/Side-Nav";
import PageWrapper from "./components/sidenav/Page-Wrapper";
import MarginWidthWrapper from "./components/sidenav/Margin-Width-Wrapper";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Reverie",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const authToken = cookieStore.get("authToken")?.value;

  const isAuth = (): boolean => {
    return !!authToken;
  };

  return (
    <html lang="en">
      <body>
        <Providers>
          {isAuth() ? (
            <div className="flex">
              <SideNav />
              <main className="flex-1 flex-wrap overflow-x-hidden">
                <MarginWidthWrapper>
                  <Header />
                  <HeaderMobile />
                  <PageWrapper>{children}</PageWrapper>
                </MarginWidthWrapper>
              </main>
            </div>
          ) : (
            <>
              <main>{children}</main>
            </>
          )}
        </Providers>
      </body>
    </html>
  );
}
